function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // objPrtPlayer
	global.__objectDepths[1] = 10; // objX
	global.__objectDepths[2] = 10; // objectZ
	global.__objectDepths[3] = 11; // objPlayerGhost
	global.__objectDepths[4] = 0; // objEffect
	global.__objectDepths[5] = 0; // objXBuster
	global.__objectDepths[6] = 0; // objPrtWeapon
	global.__objectDepths[7] = 0; // objPrtPlayerWeapon
	global.__objectDepths[8] = 0; // objXWeapon
	global.__objectDepths[9] = 20; // objPrtMovingPlatform
	global.__objectDepths[10] = 19; // objTopLadder
	global.__objectDepths[11] = 20; // objLadder
	global.__objectDepths[12] = -20; // objStaticBlock
	global.__objectDepths[13] = 0; // objPrtSolid
	global.__objectDepths[14] = 20; // objVLifter
	global.__objectDepths[15] = 20; // objHLifter
	global.__objectDepths[16] = 19; // objRailLifter
	global.__objectDepths[17] = 21; // objPolygonRail
	global.__objectDepths[18] = 0; // objPrtPath
	global.__objectDepths[19] = 0; // objPrtEffect
	global.__objectDepths[20] = 0; // objPrtPlayerEffect
	global.__objectDepths[21] = 0; // objCamera
	global.__objectDepths[22] = 0; // objSectionTop
	global.__objectDepths[23] = 0; // objSectionBottom
	global.__objectDepths[24] = 0; // objSectionRight
	global.__objectDepths[25] = 0; // objSectionLeft
	global.__objectDepths[26] = 0; // objLeftArrow
	global.__objectDepths[27] = 0; // objRightArrow
	global.__objectDepths[28] = 0; // objUpArrow
	global.__objectDepths[29] = 0; // objDownArrow
	global.__objectDepths[30] = 0; // objArrow
	global.__objectDepths[31] = 0; // objPrtEnemy
	global.__objectDepths[32] = 0; // objPrtBuster1
	global.__objectDepths[33] = 0; // objPrtWater
	global.__objectDepths[34] = 0; // objPrtIce
	global.__objectDepths[35] = 0; // objPrtThorns
	global.__objectDepths[36] = -7; // obj_skyclaw
	global.__objectDepths[37] = -7; // obj_megaturtoid2
	global.__objectDepths[38] = -7; // obj_megaturtoid1
	global.__objectDepths[39] = -21; // obj_megaturtoid_shot
	global.__objectDepths[40] = -7; // obj_hoganmer
	global.__objectDepths[41] = -8; // obj_kigman_escudo
	global.__objectDepths[42] = -21; // obj_knightman_bola
	global.__objectDepths[43] = -21; // obj_knightman_bola0
	global.__objectDepths[44] = -7; // obj_knightman_chain_dead
	global.__objectDepths[45] = -7; // obj_knightman_chain
	global.__objectDepths[46] = -5; // obj_dodgeblaster_shot
	global.__objectDepths[47] = -7; // obj_dodgeblaster_l
	global.__objectDepths[48] = -7; // obj_dodgeblaster_r
	global.__objectDepths[49] = 0; // obj_seaattacker_bubbles
	global.__objectDepths[50] = -7; // obj_seaattacker
	global.__objectDepths[51] = -7; // obj_sinefaller
	global.__objectDepths[52] = -8; // obj_flammingle
	global.__objectDepths[53] = 0; // obj_flammingle_shot
	global.__objectDepths[54] = -7; // obj_lumberjack
	global.__objectDepths[55] = -80; // obj_lumberjack_platform
	global.__objectDepths[56] = 0; // obj_lumberjack_disc
	global.__objectDepths[57] = 0; // lumber_disc1
	global.__objectDepths[58] = 0; // lumber_disc2
	global.__objectDepths[59] = -7; // obj_madpecker
	global.__objectDepths[60] = -7; // obj_bombbeen
	global.__objectDepths[61] = 0; // obj_bombbeen_shot
	global.__objectDepths[62] = -7; // obj_gunvolt
	global.__objectDepths[63] = 0; // obj_gunvolt_volt
	global.__objectDepths[64] = 0; // obj_gunvolt_misil
	global.__objectDepths[65] = -7; // objRockEnemy
	global.__objectDepths[66] = 0; // objRock
	global.__objectDepths[67] = 0; // objHomingRock
	global.__objectDepths[68] = -5; // obj_metcolo
	global.__objectDepths[69] = -5; // obj_tornadoboy
	global.__objectDepths[70] = -5; // obj_sonicdog1
	global.__objectDepths[71] = -5; // obj_sonicdog2
	global.__objectDepths[72] = -5; // bal_sonicdog1
	global.__objectDepths[73] = -10; // bal_sonicdog
	global.__objectDepths[74] = -25; // obj_rollinggabyool
	global.__objectDepths[75] = -7; // obj_ball_de_voux
	global.__objectDepths[76] = -7; // obj_fixed_robot
	global.__objectDepths[77] = -5; // obj_flamecannon
	global.__objectDepths[78] = 0; // obj_flamecannon_shot
	global.__objectDepths[79] = -7; // obj_amenhopper
	global.__objectDepths[80] = -7; // obj_raybit
	global.__objectDepths[81] = 0; // obj_raybit_shot
	global.__objectDepths[82] = -7; // obj_snowshooter
	global.__objectDepths[83] = 0; // obj_snowball
	global.__objectDepths[84] = -7; // obj_butterfly
	global.__objectDepths[85] = -7; // obj_rider
	global.__objectDepths[86] = -7; // obj_mettool
	global.__objectDepths[87] = 0; // obj_mettooll_shot
	global.__objectDepths[88] = -7; // obj_eggcreeper
	global.__objectDepths[89] = -7; // obj_creeper
	global.__objectDepths[90] = -7; // obj_falling_iworm
	global.__objectDepths[91] = -7; // obj_iworm
	global.__objectDepths[92] = -7; // obj_planty
	global.__objectDepths[93] = -7; // obj_minero
	global.__objectDepths[94] = -21; // obj_minero_arma
	global.__objectDepths[95] = -7; // obj_bird
	global.__objectDepths[96] = -7; // obj_slidecannon
	global.__objectDepths[97] = 0; // obj_slidecannon_shot
	global.__objectDepths[98] = -7; // obj_jamminger
	global.__objectDepths[99] = -7; // obj_ladderyadder
	global.__objectDepths[100] = -7; // obj_cannon
	global.__objectDepths[101] = -5; // obj_cannon_shot
	global.__objectDepths[102] = -7; // obj_cannonturn
	global.__objectDepths[103] = -7; // obj_cannonturn_up
	global.__objectDepths[104] = -12; // obj_cannonturn_shot
	global.__objectDepths[105] = -7; // obj_bat_big
	global.__objectDepths[106] = -7; // obj_bat
	global.__objectDepths[107] = -7; // obj_fallinglava
	global.__objectDepths[108] = -7; // obj_crusher
	global.__objectDepths[109] = 0; // obj_crusher_pedra4
	global.__objectDepths[110] = 0; // obj_crusher_pedra3
	global.__objectDepths[111] = 0; // obj_crusher_pedra2
	global.__objectDepths[112] = 0; // obj_crusher_pedra1
	global.__objectDepths[113] = -11; // obj_tombot
	global.__objectDepths[114] = 0; // obj_tombot_shot
	global.__objectDepths[115] = -8; // obj_spiky
	global.__objectDepths[116] = -7; // obj_roadattacker
	global.__objectDepths[117] = 0; // obj_roadattacker_shot
	global.__objectDepths[118] = -7; // obj_harpoon_serpent
	global.__objectDepths[119] = -7; // objLaserShoot
	global.__objectDepths[120] = 0; // objLaserShootWeapon
	global.__objectDepths[121] = 0; // obj_laserhorizontal
	global.__objectDepths[122] = -7; // obj_shark
	global.__objectDepths[123] = -7; // obj_wheelhog
	global.__objectDepths[124] = -7; // obj_jellyfish
	global.__objectDepths[125] = -7; // obj_joy
	global.__objectDepths[126] = -12; // obj_joy_shot
	global.__objectDepths[127] = -7; // obj_scriver
	global.__objectDepths[128] = -7; // obj_notorbanger
	global.__objectDepths[129] = -21; // obj_notorbanger_shot
	global.__objectDepths[130] = -7; // obj_iceguy
	global.__objectDepths[131] = -7; // obj_tankcar
	global.__objectDepths[132] = 0; // obj_tankcar_shot
	global.__objectDepths[133] = -7; // obj_iceman
	global.__objectDepths[134] = 0; // obj_iceman_shot
	global.__objectDepths[135] = -7; // obj_gunshot
	global.__objectDepths[136] = -7; // obj_headgunner_customer
	global.__objectDepths[137] = -21; // obj_gunshot_shot1
	global.__objectDepths[138] = 0; // obj_gunshot_shot
	global.__objectDepths[139] = -7; // obj_alien
	global.__objectDepths[140] = 0; // obj_alien_shot
	global.__objectDepths[141] = -7; // objSpinwall
	global.__objectDepths[142] = -10; // objSpinWallSolid
	global.__objectDepths[143] = -7; // obj_gulpfer
	global.__objectDepths[144] = 0; // obj_gulpfer_die1
	global.__objectDepths[145] = 0; // obj_gulpfer_die2
	global.__objectDepths[146] = 0; // obj_gulpfer_bubbles
	global.__objectDepths[147] = 0; // obj_bit_disco
	global.__objectDepths[148] = -6; // objBit
	global.__objectDepths[149] = -8; // obj_zerob_shotB
	global.__objectDepths[150] = -8; // obj_zerob_shotA
	global.__objectDepths[151] = -10; // obj_zerob_shotC
	global.__objectDepths[152] = -9; // objZeroBoss
	global.__objectDepths[153] = -55; // objChillPin
	global.__objectDepths[154] = -9; // objChillIce1
	global.__objectDepths[155] = 0; // objChillIce2
	global.__objectDepths[156] = 0; // objChillIce3
	global.__objectDepths[157] = 0; // objChillIce4
	global.__objectDepths[158] = -56; // objChillSnow
	global.__objectDepths[159] = 0; // objChillRocks
	global.__objectDepths[160] = -8; // objChillPenguin
	global.__objectDepths[161] = -2; // obj_armadillo_flash
	global.__objectDepths[162] = -2; // obj_armadillo_shot
	global.__objectDepths[163] = -8; // objArmoredArmadillo
	global.__objectDepths[164] = 0; // obj_hf_storm_hori
	global.__objectDepths[165] = 0; // obj_hf_storm_vert
	global.__objectDepths[166] = 0; // hur_vaclt
	global.__objectDepths[167] = -8; // objStormEagleDiveAtkR
	global.__objectDepths[168] = -8; // objStormEagleDiveAtkL
	global.__objectDepths[169] = 0; // obj_hf_ovo
	global.__objectDepths[170] = -8; // obj_hf_birds
	global.__objectDepths[171] = -6; // objStormEagle
	global.__objectDepths[172] = -5; // obj_moleborer
	global.__objectDepths[173] = -5; // sub_hunteracid
	global.__objectDepths[174] = -5; // bal_hunteracid1
	global.__objectDepths[175] = -12; // bal_1
	global.__objectDepths[176] = -5; // bal_hunteracid
	global.__objectDepths[177] = -5; // est_acid
	global.__objectDepths[178] = -5; // est_acid1
	global.__objectDepths[179] = -5; // est_acid2
	global.__objectDepths[180] = -5; // est_dash
	global.__objectDepths[181] = -25; // est_humo_01
	global.__objectDepths[182] = -25; // est_humo_02
	global.__objectDepths[183] = -20; // dead_brillo_boss
	global.__objectDepths[184] = -6; // obj_sub_rt_55
	global.__objectDepths[185] = -21; // obj_subboss_shot
	global.__objectDepths[186] = -21; // obj_subboss_chain
	global.__objectDepths[187] = -44; // obj_madgrinder
	global.__objectDepths[188] = -5; // obj_beeblader
	global.__objectDepths[189] = 0; // obj_bee_missel
	global.__objectDepths[190] = 0; // obj_bee_tiros
	global.__objectDepths[191] = 0; // obj_bee_tiros_exp
	global.__objectDepths[192] = -5; // objCruiziler
	global.__objectDepths[193] = -5; // obj_cruiziler_platform
	global.__objectDepths[194] = -21; // obj_cruiziler_shot
	global.__objectDepths[195] = -5; // objEnemyExpl0
	global.__objectDepths[196] = -5; // objEnemyExpl1
	global.__objectDepths[197] = -9; // objEnemyExpl2
	global.__objectDepths[198] = -16; // objExplBlue
	global.__objectDepths[199] = -8; // objExplOrange
	global.__objectDepths[200] = -8; // objWaterTornado
	global.__objectDepths[201] = 0; // objTornadoParts
	global.__objectDepths[202] = -5; // objSmoke
	global.__objectDepths[203] = 0; // obj_title
	global.__objectDepths[204] = 0; // mmx_title
	global.__objectDepths[205] = 0; // B2rform
	global.__objectDepths[206] = 0; // mmx_title_shoot
	global.__objectDepths[207] = 2; // obj_title_anim
	global.__objectDepths[208] = 0; // FadeOut
	global.__objectDepths[209] = 0; // FadeIn
	global.__objectDepths[210] = 0; // obj_key_config1
	global.__objectDepths[211] = 0; // obj_key_config2
	global.__objectDepths[212] = 1; // draw_option
	global.__objectDepths[213] = 0; // obj_option
	global.__objectDepths[214] = 0; // obj_capcom_logo
	global.__objectDepths[215] = 0; // obj_spec_animation
	global.__objectDepths[216] = 0; // objController
	global.__objectDepths[217] = 0; // objDebug
	global.__objectDepths[218] = 0; // objRoomControl
	global.__objectDepths[219] = -98; // objPauseController
	global.__objectDepths[220] = -99; // objPauseDraw
	global.__objectDepths[221] = -97; // objTimerControl
	global.__objectDepths[222] = 0; // objStartVariables
	global.__objectDepths[223] = 0; // objPlayerSelMenu
	global.__objectDepths[224] = 0; // objLoading
	global.__objectDepths[225] = 0; // objVersusControl
	global.__objectDepths[226] = -100; // objVersusMenuEnd
	global.__objectDepths[227] = 0; // JumpALL


	global.__objectNames[0] = "objPrtPlayer";
	global.__objectNames[1] = "objX";
	global.__objectNames[2] = "objectZ";
	global.__objectNames[3] = "objPlayerGhost";
	global.__objectNames[4] = "objEffect";
	global.__objectNames[5] = "objXBuster";
	global.__objectNames[6] = "objPrtWeapon";
	global.__objectNames[7] = "objPrtPlayerWeapon";
	global.__objectNames[8] = "objXWeapon";
	global.__objectNames[9] = "objPrtMovingPlatform";
	global.__objectNames[10] = "objTopLadder";
	global.__objectNames[11] = "objLadder";
	global.__objectNames[12] = "objStaticBlock";
	global.__objectNames[13] = "objPrtSolid";
	global.__objectNames[14] = "objVLifter";
	global.__objectNames[15] = "objHLifter";
	global.__objectNames[16] = "objRailLifter";
	global.__objectNames[17] = "objPolygonRail";
	global.__objectNames[18] = "objPrtPath";
	global.__objectNames[19] = "objPrtEffect";
	global.__objectNames[20] = "objPrtPlayerEffect";
	global.__objectNames[21] = "objCamera";
	global.__objectNames[22] = "objSectionTop";
	global.__objectNames[23] = "objSectionBottom";
	global.__objectNames[24] = "objSectionRight";
	global.__objectNames[25] = "objSectionLeft";
	global.__objectNames[26] = "objLeftArrow";
	global.__objectNames[27] = "objRightArrow";
	global.__objectNames[28] = "objUpArrow";
	global.__objectNames[29] = "objDownArrow";
	global.__objectNames[30] = "objArrow";
	global.__objectNames[31] = "objPrtEnemy";
	global.__objectNames[32] = "objPrtBuster1";
	global.__objectNames[33] = "objPrtWater";
	global.__objectNames[34] = "objPrtIce";
	global.__objectNames[35] = "objPrtThorns";
	global.__objectNames[36] = "obj_skyclaw";
	global.__objectNames[37] = "obj_megaturtoid2";
	global.__objectNames[38] = "obj_megaturtoid1";
	global.__objectNames[39] = "obj_megaturtoid_shot";
	global.__objectNames[40] = "obj_hoganmer";
	global.__objectNames[41] = "obj_kigman_escudo";
	global.__objectNames[42] = "obj_knightman_bola";
	global.__objectNames[43] = "obj_knightman_bola0";
	global.__objectNames[44] = "obj_knightman_chain_dead";
	global.__objectNames[45] = "obj_knightman_chain";
	global.__objectNames[46] = "obj_dodgeblaster_shot";
	global.__objectNames[47] = "obj_dodgeblaster_l";
	global.__objectNames[48] = "obj_dodgeblaster_r";
	global.__objectNames[49] = "obj_seaattacker_bubbles";
	global.__objectNames[50] = "obj_seaattacker";
	global.__objectNames[51] = "obj_sinefaller";
	global.__objectNames[52] = "obj_flammingle";
	global.__objectNames[53] = "obj_flammingle_shot";
	global.__objectNames[54] = "obj_lumberjack";
	global.__objectNames[55] = "obj_lumberjack_platform";
	global.__objectNames[56] = "obj_lumberjack_disc";
	global.__objectNames[57] = "lumber_disc1";
	global.__objectNames[58] = "lumber_disc2";
	global.__objectNames[59] = "obj_madpecker";
	global.__objectNames[60] = "obj_bombbeen";
	global.__objectNames[61] = "obj_bombbeen_shot";
	global.__objectNames[62] = "obj_gunvolt";
	global.__objectNames[63] = "obj_gunvolt_volt";
	global.__objectNames[64] = "obj_gunvolt_misil";
	global.__objectNames[65] = "objRockEnemy";
	global.__objectNames[66] = "objRock";
	global.__objectNames[67] = "objHomingRock";
	global.__objectNames[68] = "obj_metcolo";
	global.__objectNames[69] = "obj_tornadoboy";
	global.__objectNames[70] = "obj_sonicdog1";
	global.__objectNames[71] = "obj_sonicdog2";
	global.__objectNames[72] = "bal_sonicdog1";
	global.__objectNames[73] = "bal_sonicdog";
	global.__objectNames[74] = "obj_rollinggabyool";
	global.__objectNames[75] = "obj_ball_de_voux";
	global.__objectNames[76] = "obj_fixed_robot";
	global.__objectNames[77] = "obj_flamecannon";
	global.__objectNames[78] = "obj_flamecannon_shot";
	global.__objectNames[79] = "obj_amenhopper";
	global.__objectNames[80] = "obj_raybit";
	global.__objectNames[81] = "obj_raybit_shot";
	global.__objectNames[82] = "obj_snowshooter";
	global.__objectNames[83] = "obj_snowball";
	global.__objectNames[84] = "obj_butterfly";
	global.__objectNames[85] = "obj_rider";
	global.__objectNames[86] = "obj_mettool";
	global.__objectNames[87] = "obj_mettooll_shot";
	global.__objectNames[88] = "obj_eggcreeper";
	global.__objectNames[89] = "obj_creeper";
	global.__objectNames[90] = "obj_falling_iworm";
	global.__objectNames[91] = "obj_iworm";
	global.__objectNames[92] = "obj_planty";
	global.__objectNames[93] = "obj_minero";
	global.__objectNames[94] = "obj_minero_arma";
	global.__objectNames[95] = "obj_bird";
	global.__objectNames[96] = "obj_slidecannon";
	global.__objectNames[97] = "obj_slidecannon_shot";
	global.__objectNames[98] = "obj_jamminger";
	global.__objectNames[99] = "obj_ladderyadder";
	global.__objectNames[100] = "obj_cannon";
	global.__objectNames[101] = "obj_cannon_shot";
	global.__objectNames[102] = "obj_cannonturn";
	global.__objectNames[103] = "obj_cannonturn_up";
	global.__objectNames[104] = "obj_cannonturn_shot";
	global.__objectNames[105] = "obj_bat_big";
	global.__objectNames[106] = "obj_bat";
	global.__objectNames[107] = "obj_fallinglava";
	global.__objectNames[108] = "obj_crusher";
	global.__objectNames[109] = "obj_crusher_pedra4";
	global.__objectNames[110] = "obj_crusher_pedra3";
	global.__objectNames[111] = "obj_crusher_pedra2";
	global.__objectNames[112] = "obj_crusher_pedra1";
	global.__objectNames[113] = "obj_tombot";
	global.__objectNames[114] = "obj_tombot_shot";
	global.__objectNames[115] = "obj_spiky";
	global.__objectNames[116] = "obj_roadattacker";
	global.__objectNames[117] = "obj_roadattacker_shot";
	global.__objectNames[118] = "obj_harpoon_serpent";
	global.__objectNames[119] = "objLaserShoot";
	global.__objectNames[120] = "objLaserShootWeapon";
	global.__objectNames[121] = "obj_laserhorizontal";
	global.__objectNames[122] = "obj_shark";
	global.__objectNames[123] = "obj_wheelhog";
	global.__objectNames[124] = "obj_jellyfish";
	global.__objectNames[125] = "obj_joy";
	global.__objectNames[126] = "obj_joy_shot";
	global.__objectNames[127] = "obj_scriver";
	global.__objectNames[128] = "obj_notorbanger";
	global.__objectNames[129] = "obj_notorbanger_shot";
	global.__objectNames[130] = "obj_iceguy";
	global.__objectNames[131] = "obj_tankcar";
	global.__objectNames[132] = "obj_tankcar_shot";
	global.__objectNames[133] = "obj_iceman";
	global.__objectNames[134] = "obj_iceman_shot";
	global.__objectNames[135] = "obj_gunshot";
	global.__objectNames[136] = "obj_headgunner_customer";
	global.__objectNames[137] = "obj_gunshot_shot1";
	global.__objectNames[138] = "obj_gunshot_shot";
	global.__objectNames[139] = "obj_alien";
	global.__objectNames[140] = "obj_alien_shot";
	global.__objectNames[141] = "objSpinwall";
	global.__objectNames[142] = "objSpinWallSolid";
	global.__objectNames[143] = "obj_gulpfer";
	global.__objectNames[144] = "obj_gulpfer_die1";
	global.__objectNames[145] = "obj_gulpfer_die2";
	global.__objectNames[146] = "obj_gulpfer_bubbles";
	global.__objectNames[147] = "obj_bit_disco";
	global.__objectNames[148] = "objBit";
	global.__objectNames[149] = "obj_zerob_shotB";
	global.__objectNames[150] = "obj_zerob_shotA";
	global.__objectNames[151] = "obj_zerob_shotC";
	global.__objectNames[152] = "objZeroBoss";
	global.__objectNames[153] = "objChillPin";
	global.__objectNames[154] = "objChillIce1";
	global.__objectNames[155] = "objChillIce2";
	global.__objectNames[156] = "objChillIce3";
	global.__objectNames[157] = "objChillIce4";
	global.__objectNames[158] = "objChillSnow";
	global.__objectNames[159] = "objChillRocks";
	global.__objectNames[160] = "objChillPenguin";
	global.__objectNames[161] = "obj_armadillo_flash";
	global.__objectNames[162] = "obj_armadillo_shot";
	global.__objectNames[163] = "objArmoredArmadillo";
	global.__objectNames[164] = "obj_hf_storm_hori";
	global.__objectNames[165] = "obj_hf_storm_vert";
	global.__objectNames[166] = "hur_vaclt";
	global.__objectNames[167] = "objStormEagleDiveAtkR";
	global.__objectNames[168] = "objStormEagleDiveAtkL";
	global.__objectNames[169] = "obj_hf_ovo";
	global.__objectNames[170] = "obj_hf_birds";
	global.__objectNames[171] = "objStormEagle";
	global.__objectNames[172] = "obj_moleborer";
	global.__objectNames[173] = "sub_hunteracid";
	global.__objectNames[174] = "bal_hunteracid1";
	global.__objectNames[175] = "bal_1";
	global.__objectNames[176] = "bal_hunteracid";
	global.__objectNames[177] = "est_acid";
	global.__objectNames[178] = "est_acid1";
	global.__objectNames[179] = "est_acid2";
	global.__objectNames[180] = "est_dash";
	global.__objectNames[181] = "est_humo_01";
	global.__objectNames[182] = "est_humo_02";
	global.__objectNames[183] = "dead_brillo_boss";
	global.__objectNames[184] = "obj_sub_rt_55";
	global.__objectNames[185] = "obj_subboss_shot";
	global.__objectNames[186] = "obj_subboss_chain";
	global.__objectNames[187] = "obj_madgrinder";
	global.__objectNames[188] = "obj_beeblader";
	global.__objectNames[189] = "obj_bee_missel";
	global.__objectNames[190] = "obj_bee_tiros";
	global.__objectNames[191] = "obj_bee_tiros_exp";
	global.__objectNames[192] = "objCruiziler";
	global.__objectNames[193] = "obj_cruiziler_platform";
	global.__objectNames[194] = "obj_cruiziler_shot";
	global.__objectNames[195] = "objEnemyExpl0";
	global.__objectNames[196] = "objEnemyExpl1";
	global.__objectNames[197] = "objEnemyExpl2";
	global.__objectNames[198] = "objExplBlue";
	global.__objectNames[199] = "objExplOrange";
	global.__objectNames[200] = "objWaterTornado";
	global.__objectNames[201] = "objTornadoParts";
	global.__objectNames[202] = "objSmoke";
	global.__objectNames[203] = "obj_title";
	global.__objectNames[204] = "mmx_title";
	global.__objectNames[205] = "B2rform";
	global.__objectNames[206] = "mmx_title_shoot";
	global.__objectNames[207] = "obj_title_anim";
	global.__objectNames[208] = "FadeOut";
	global.__objectNames[209] = "FadeIn";
	global.__objectNames[210] = "obj_key_config1";
	global.__objectNames[211] = "obj_key_config2";
	global.__objectNames[212] = "draw_option";
	global.__objectNames[213] = "obj_option";
	global.__objectNames[214] = "obj_capcom_logo";
	global.__objectNames[215] = "obj_spec_animation";
	global.__objectNames[216] = "objController";
	global.__objectNames[217] = "objDebug";
	global.__objectNames[218] = "objRoomControl";
	global.__objectNames[219] = "objPauseController";
	global.__objectNames[220] = "objPauseDraw";
	global.__objectNames[221] = "objTimerControl";
	global.__objectNames[222] = "objStartVariables";
	global.__objectNames[223] = "objPlayerSelMenu";
	global.__objectNames[224] = "objLoading";
	global.__objectNames[225] = "objVersusControl";
	global.__objectNames[226] = "objVersusMenuEnd";
	global.__objectNames[227] = "JumpALL";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
